version: 2

sources:

    - name: source

      database: wallywd_s3_db

      schema: BRONZE

      tables:

        - name: fact_COPY

    - name: xfm

      database: wallywd_s3_db

      schema: SILVER

      tables:

        - name: fact_TRANSFORM


    